graph TD;
  A-->|foo|B;
  A-->C;
  B-->D;
  C-->D;
  D-->E;
  E-->F;
  F-->G;
  G-->H;
  H-->I;
  I-->J;
  J-->K;
  K-->L;
  L-->M;
  linkStyle default fill:none,stroke:#0D47A1,stroke-width:2px;
  classDef default fill:#B3E5FC,stroke:#0D47A1,stroke-width:2px;
